<a href="https://colab.research.google.com/github/balaMantasha/AI-ML-Projects/blob/main/flight_prediction_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import random
random.seed(2)
df = pd.read_csv('Clean_Dataset.csv')
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
# ! pip install ydata_profiling
# import matplotlib.pyplot as plt
# from ydata_profiling import ProfileReport
# profile = ProfileReport(df)
# profile.to_file('flightprice.html')

In [ ]:
# from google.colab import files
# files.download('flightprice.html')

In [ ]:
# unwanted columns
df = df.drop(['Unnamed: 0' , 'flight'], axis =1)
df

,airline,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...
300148,Vistara,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [ ]:
# Convert categorical variables to dummy variables
df = pd.get_dummies(df, columns=['airline', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city' , 'class'])
df

,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara,source_city_Bangalore,...,arrival_time_Morning,arrival_time_Night,destination_city_Bangalore,destination_city_Chennai,destination_city_Delhi,destination_city_Hyderabad,destination_city_Kolkata,destination_city_Mumbai,class_Business,class_Economy
0,2.17,1,5953,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,True,False,True
1,2.33,1,5953,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,True,False,True
2,2.17,1,5956,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
3,2.25,1,5955,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,True
4,2.33,1,5955,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,10.08,49,69265,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300149,10.42,49,77105,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300150,13.83,49,79099,False,False,False,False,False,True,False,...,False,True,False,False,False,True,False,False,True,False
300151,10.00,49,81585,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
300152,10.08,49,81585,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False

In [ ]:
# Separate features and target
X = df.drop(['price'], axis=1)
y = df['price']

In [ ]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Standardize the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Models to evaluate

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
import joblib

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'Decision Tree Regression': DecisionTreeRegressor(),
    'Random Forest Regression': RandomForestRegressor(),
    'Gradient Boosting Regression': GradientBoostingRegressor(),
     'Support Vector Regression': SVR(),
    'K-Nearest Neighbors Regression': KNeighborsRegressor(),
    'Extra Trees Regression': ExtraTreesRegressor(),
    'AdaBoost Regression': AdaBoostRegressor()
}

# Parameters for Ridge and Lasso regression
ridge_params = {'alpha': [0.1, 1.0 ,10]}
lasso_params = {'alpha': [0.1, 1.0 ,10]}

# Grid search for Ridge and Lasso
ridge_grid = GridSearchCV(models['Ridge Regression'], ridge_params, cv=3, scoring='neg_mean_squared_error')
ridge_grid.fit(X_train, y_train)
print("Ridge Regression Best Parameters:", ridge_grid.best_params_)

lasso_grid = GridSearchCV(models['Lasso Regression'], lasso_params, cv=3, scoring='neg_mean_squared_error')
lasso_grid.fit(X_train, y_train)
print("Lasso Regression Best Parameters:", lasso_grid.best_params_)

# Train and evaluate all models
results = {}
for name, model in models.items():
    if name == 'Linear Regression':
        model.fit(X_train, y_train)
    elif name == 'Ridge Regression':
        model.set_params(**ridge_grid.best_params_)
        model.fit(X_train, y_train)
    elif name == 'Lasso Regression':
        model.set_params(**lasso_grid.best_params_)
        model.fit(X_train, y_train)
    else:
        model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    results[name] = {'MSE': mse, 'R^2': r2, 'MAE':mae}

# Print results
for name, result in results.items():
    print(f'{name}:')
    print(f'  MSE: {result["MSE"]}')
    print(f'  R^2: {result["R^2"]}')
    print(f'  MAE: {result["MAE"]}')

Ridge Regression Best Parameters: {'alpha': 10}

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.416e+10, tolerance: 8.245e+09
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.824e+10, tolerance: 8.239e+09
  model = cd_fast.enet_coordinate_descent(

Lasso Regression Best Parameters: {'alpha': 0.1}
Linear Regression:
  MSE: 45720738.528572276
  R^2: 0.9113049257503447
  MAE: 4553.726142992456
Ridge Regression:
  MSE: 45720756.135375045
  R^2: 0.9113048915943637
  MAE: 4553.281956131712
Lasso Regression:
  MSE: 45720767.34192062
  R^2: 0.9113048698544395
  MAE: 4553.247650366481
Decision Tree Regression:
  MSE: 12518888.095442818
  R^2: 0.9757142219289715
  MAE: 1166.6615221024695
Random Forest Regression:
  MSE: 7742442.963536854
  R^2: 0.9849801955168447
  MAE: 1075.5092134000188
Gradient Boosting Regression:
  MSE: 24980177.45387817
  R^2: 0.9515401814286818
  MAE: 2947.8848258500902
Support Vector Regression:
  MSE: 482546487.3507004
  R^2: 0.0638931499819495
  MAE: 13272.411540945257
K-Nearest Neighbors Regression:
  MSE: 14983315.51749463
  R^2: 0.9709334029786133
  MAE: 1821.9868201429263
Extra Trees Regression:
  MSE: 8767186.319641551
  R^2: 0.9829922641976744
  MAE: 1128.1703512376448
AdaBoost Regression:
  MSE: 35641526.86989694
  R^2: 0.9308579000726105
  MAE: 3824.4420649088215

In [ ]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib

# Define hyperparameters grid for RandomForestRegressor
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# Initialize the RandomForestRegressor
rf = RandomForestRegressor()

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Print the best parameters found by the grid search
print("Best Parameters:", grid_search.best_params_)

# Train the RandomForestRegressor with the best parameters
best_rf = grid_search.best_estimator_
best_rf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_rf.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print('Random Forest Regression with Hyperparameter Tuning:')
print(f'  MSE: {mse}')
print(f'  R^2: {r2}')
print(f'  MAE: {mae}')

NameError: name 'X_train' is not defined